
// WINDOWS
  var windows = <Map<String, dynamic>>[
    {
      "prodId": 01,
      "name": "Metallic Window",
      "price": 500000 - 600000,
      "image": "assets/images/w1.jpg",
      "description": "Very durable product made from the finest materials.",
    },
    {
      "prodId": 02,
      "name": "Metallic Window",
      "price": 500000 - 600000,
      "image": "assets/images/w2.jpg",
      "description": "Very durable product made from the finest materials.",
    },
    {
      "prodId": 03,
      "name": "Metallic Window",
      "price": 500000 - 600000,
      "image": "assets/images/w5.jpg",
      "description": "Very durable product made from the finest materials.",
    },
    {
      "prodId": 04,
      "name": "Metallic Window",
      "price": 500000 - 600000,
      "image": "assets/images/w6.jpg",
      "description": "Very durable product made from the finest materials.",
    },
    {
      "prodId": 05,
      "name": "Metallic Window",
      "price": 500000 - 600000,
      "image": "assets/images/window.jpeg",
      "description": "Very durable product made from the finest materials.",
    },
    {
      "prodId": 06,
      "name": "Metallic Window",
      "price": 500000 - 600000,
      "image": "assets/images/window1.jpeg",
      "description": "Very durable product made from the finest materials.",
    },
    {
      "prodId": 06,
      "name": "Metallic Window",
      "price": 500000 - 600000,
      "image": "assets/images/window2.jpeg",
      "description": "Very durable product made from the finest materials.",
    },
    {
      "prodId": 06,
      "name": "Metallic Window",
      "price": 500000 - 600000,
      "image": "assets/images/window3.jpeg",
      "description": "Very durable product made from the finest materials.",
    },
    {
      "prodId": 06,
      "name": "Metallic Window",
      "price": 500000 - 600000,
      "image": "assets/images/window4.jpeg",
      "description": "Very durable product made from the finest materials.",
    },
    {
      "prodId": 06,
      "name": "Metallic Window",
      "price": 500000 - 600000,
      "image": "assets/images/window5.jpeg",
      "description": "Very durable product made from the finest materials.",
    },
    {
      "prodId": 06,
      "name": "Metallic Window",
      "price": 500000 - 600000,
      "image": "assets/images/window5.jpg",
      "description": "Very durable product made from the finest materials.",
    },
  ];
